### ISSUE TITLE
Cypress tests are broken

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#171]
Noting a bunch of issues I ran into with Cypress tests:
- `yarn test:apps` pops up a window of the Cypress desktop app, where I can click "run all tests" (or something like that). Clicking that, a Chrome window is opened. But then there is no further indication that anything is happening. This may be an issue with my local Cypress setup?
- What needs to be run before we can do `yarn test:app:partners`? I tried running `yarn dev:backend` or `yarn dev:all` (in a separate terminal), but got errors in both cases.

Completion criteria:
- [x] `yarn test:apps` sounds like it runs tests for both the `public` and `partners` sites; it doesn't (it only runs `public` tests
- [x] get e2e tests working in bloom-housing/bloom
- [x] create instructions for running Cypress tests
- [x] There's no `yarn` command to run the tests in "headless" mode
- [x] When I was able to get the `public` Cypress tests running (in headless mode), 48 of 94 tests failed (across 20 different test specs, of 23 total)
- [x] A compilation error is blocking even being able to run the `partners` Cypress tests.
- [x] Add tests to presubmit

**Comment by avaleske** [comment]
@anders-schneider noted that these are broken upstream as well. Deprioritizing for now.

**Comment by willrlin** [comment]
Sean said that these tests are passing on their `dev` and `master` branches, so it must be something about our set up that is causing them to fail.

**Comment by willrlin** [comment]
I was able to get the tests to run and pass in Bloom's codebase and then fail in ours. I started a wiki page with some instructions: https://github.com/CityOfDetroit/bloom/wiki/Cypress-tests

**Comment by willrlin** [comment]
Most of the failing `sites/public` tests have to do with applications. I wonder if we should attempt to fix or just disable them.

**Comment by willrlin** [comment]
It looks like there's only 1 test in `sites/partners`, which is broken in bloom-housing/bloom. This is also probably why `yarn test:apps` only runs `sites/public`.

**Comment by willrlin** [comment]
The .circleci config also only runs `sites/public` cypress tests.

**Comment by willrlin** [comment]
I was able to get interactive mode working. @anders-schneider did you do `cypress open` from your `sites/public` directory? It automatically showed up with a list of all the tests available to run for me.

**Comment by willrlin** [comment]
Debugging in interactive mode showed that the response from the server was now a PaginatedListing instead of just a Listing[], so we need to select the items.

**Comment by willrlin** [comment]
@avaleske you may be interested in the fix if the cypress tests are failing when you add pagination upstream.

**Comment by willrlin** [comment]
Status: all the tests are passing but I can't seem to get the Travis config just right. I'm trying to parallelize it and using [this example](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.travis.yml) but it's hard to understand and I can't find good `.travis.yml` documentation anywhere about these options. I'm also putting some notes in [the wiki](https://github.com/CityOfDetroit/bloom/wiki/Cypress-tests).

**Comment by willrlin** [comment]
I disabled the portion of `member.spec.ts` that was flaky and merged the rest of the tests. I don't know that it's worth it to re-enable if we aren't going to have applications.
