### ISSUE TITLE
Contribute v0 of filters upstream

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#192]
Blocked by #202 

- [x] Make changes needed for merging upstream
- [x] Merge Upstream (https://github.com/bloom-housing/bloom/pull/1578)
- [x] Merge contribute/avaleske-filters branch back into our fork (https://github.com/CityOfDetroit/bloom/pull/358)
- [ ] Revert pagination changes we made, to match upstream (https://github.com/CityOfDetroit/bloom/pull/353)

To reduce the pain of future merges, let's contribute v0 of our filtering and pagination work upstream.

This will probably be easiest by cherry-picking commits from `main` for each of the related branches, and then squashing them together. Otherwise, we'll need to manually build the PR by copy/pasting our changes in.

We might also want to add an environment variable the disables filters so that Exygy can leave them disabled until they're complete. (This points toward a future where we have a set of configs that enable or disable features at runtime, which could be nice for disabling applications)

**Comment by avaleske** [comment]
This also includes merging https://github.com/bloom-housing/bloom/pull/1578 back into our fork, and removing some of the changes we made to pagination now that listings uses a separate pagination query params (so the other endpoints that use it can stay defaulting to 10, instead of -1)
