### ISSUE TITLE
Unit Size Filter

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#324]
Add filtering on unit size.

Steps:
- [x] Add to backend
- [ ] Contribute backend changes upstream (Under Review)
- [ ] Add to frontend (Under Review)

Per Tom's comment below:
- Should be in a single dropdown
- Should have radio options of Studio +, 1 Bedroom +, 2 Bedrooms +, 3 Bedrooms +, 4 Bedrooms +. This will maximize the amount of results returned for the user.
- In a future phase we may want to add an option for "Show only exact match," which would constrain the results specifically to the user's selection and ignore the "+"

**Comment by avaleske** [comment]
@kar-r-green and @tomgebauer lmk when we have mocks for how unit size filtering should work, assigning to @tomgebauer for now.

**Comment by tomgebauer** [comment]
I need to mock, but I'm having some Figma issues, so wanted to clarify

- Should be in a single dropdown
- Should have **radio options** of Studio +, 1 Bedroom +, 2 Bedrooms +, 3 Bedrooms +, 4 Bedrooms +.  This will maximize the amount of results returned for the user.
- In a future phase we may want to add an option for "Show only exact match," which would constrain the results specifically to the user's selection and ignore the "+"

**Comment by avaleske** [comment]
Thanks! Unassigning you @tomgebauer and removing the blocked label
