### ISSUE TITLE
Improvements to the "Contact Leasing Agent" section of the individual-listing view

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#329]
![image](https://user-images.githubusercontent.com/8754454/128242724-35c8dd3e-c82b-4a38-b8c6-f82026363b18.png)

- [ ] Change the header to "Contact Property to Apply"
- [ ] If present, include the property manager contact details (phone number and email address)
- [ ] If present, include the property address and management company website

**Comment by anders-schneider** [comment]
Do we also want to include the management company name? (My vote: if we have it, let's include it)

**Comment by willrlin** [comment]
Re: management company, the mocks have a separate section for property management info.

**Comment by willrlin** [comment]
I think maybe we should change the "Contact Leasing Agent" section to correspond to the property management info in the mocks, and the "How to Apply" section to correspond to the "Contact Property to Apply".
