### ISSUE TITLE
Improvements to the "Features" section of the individual-listing view

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#330]
![image](https://user-images.githubusercontent.com/8754454/128243635-1da1f8ae-9525-4c8d-824f-e72079d33957.png)

- [x] Don't display the "Built" section if we don't have that data
- [x] Only show the "Neighborhood" section when the listing includes that information
- [x] Under "Unit Features", if we don't know the square footage, don't include the "square feet" text
- [x] If "Additional Fees" is empty, leave that section out, too
- [ ] If all the sections here are empty (ie we just don't have any data for this listing), indicate that we don't know anything about this listing (e.g. "no information available" banner) instead of weird empty space/sections
