### ISSUE TITLE
Eligibility questionnaire : initial iteration

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#39]
<a href="https://github.com/elenm"><img src="https://avatars.githubusercontent.com/u/16543000?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [elenm](https://github.com/elenm)**
_Wednesday Jun 09, 2021 at 14:21 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/CityOfDetroit/affordable-housing-app/issues/46_

----

 - [ ] Work with Tom to determine if it should look like the Dahlia questionnaire or build something new 
 - [ ] Work with HRD to clarify the content of the questionnaire
 - [ ] Build initial iteration

Relevant links: 
[Affordable housing map "search by income" does eligibility filtering](https://detroitmi.gov/webapp/affordable-housing-map)
[Eligibility questionnaire mocks](https://www.figma.com/proto/wAhoXVmHRIJ2TyBKFVq2JY/Mockups?node-id=249%3A2&scaling=scale-down&page-id=242%3A119)
[Dahlia eligibility estimator](https://housing.sfgov.org/eligibility-estimator/rental)
[Detroit eligibility calculator](https://www.dhcmi.org/eligibilitycalculator.aspx)
