### ISSUE TITLE
Epic: Deployment

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#53]
Tracking issue for everything related to deployment.

- [x] CityOfDetroit/affordable-housing-app#93
- [x] #86
- [x] CityOfDetroit/affordable-housing-app#92: Deploy backend/core and a DB
- [x] CityOfDetroit/affordable-housing-app#36: Set up deployment pipeline
- [x] CityOfDetroit/affordable-housing-app#71: Deploy Storybook
- [x] CityOfDetroit/affordable-housing-app#82: Get a list of services Bloom depends on
- [x] CityOfDetroit/affordable-housing-app#70: Identify Cloud provider for app
- [x] #52
- [x] #58
- [x] #109
- [ ] Download deployment config and check it in for repeatable CLI deployment
- [ ] [Bug] edit/refresh needs node_modules/ mounted, but that sometimes leads to root permission modules in the local directory
- [x] #100
- [x] #128
- [x] #129
- [x] #134
- [ ] #136

Current size estimate: 21
