### ISSUE TITLE
Set up basic Detroit configurations for Bloom

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#62]
- [x] Add Detroit title, logos, and footer
- [x] Update site color scheme for applicant portal
- [x] Update color scheme for partner portal

**Comment by tomgebauer** [comment]
@elenm also need to figure out how to get the city's font–Montserrat–into the UI. [https://github.com/CityOfDetroit/style-guide/blob/master/Montserrat.zip](https://github.com/CityOfDetroit/style-guide/blob/master/Montserrat.zip)

**Comment by willrlin** [comment]
I added #111 to track that.
