### ISSUE TITLE
Plan better gathering and displaying of accessibility information

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#67]
- [ ] check Exygy's current partner portal version
- [ ] Add more structured format for accessibility information (currently its displayed in text free form in different places on the listing)
- [ ] Add helpful information to explain accessibility requirements and how to determine if they are met

The gathering of information is TBD depending on whether we will allow property managers to create their own listings.

Product questions are remaining here about what this will look like.

**Comment by willrlin** [comment]
As a part of this task, please create the tickets for necessary front-end changes if we are going to change the structure of the a11y info in the back-end.

**Comment by ashjkim** [comment]
Hi Will - do you want me to compile the UX insights and some info that Christopher Samp from the city of Detroit sent us as to what kind of front-end changes we want to see?

**Comment by willrlin** [comment]
Yes please! We'll use it as a guiding post; we won't have all the data we'd need to fill it out, so if you also have ideas for content when there is no data, that'd be great as well!

**Comment by avaleske** [comment]
The requirements of this ticket are now reflected in
- #609
- #610 
- #611 
- #612 
- #320 

Closing this ticket as the work will be continued in those issues.
