### ISSUE TITLE
Email updates for new listings

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#68]
- [ ] Determine what this should look like (simple email list with manual involvement or something more automated and involved)
- [ ] Add email updates
- [ ] Email updates for both new listings and updates to favorited listings
