### ISSUE TITLE
[Email/SMS] Collect phone number on FE w/ validation

### ISSUE THREAD

**Issue by GabeBenjamin** [CityOfDetroit/bloom#701]
What feature is this part of?
"New Listing" Email/SMS Notifications #695 

Some questions we need to answer:
- [ ] Do we care about non-US numbers?
- [ ] How strict do we want to be with validation?
- [ ] Do we need editing phone number functionality?
- [ ] Do we need deleting phone number functionality?
