### ISSUE TITLE
[Email/SMS] Create queue/function to send sms to users

### ISSUE THREAD

**Issue by GabeBenjamin** [CityOfDetroit/bloom#705]
What feature is this part of?
"New Listing" Email/SMS Notifications #695

**Comment by anders-schneider** [comment]
The current state: the creation of a new listing will trigger SMS notifications to all opted-in users.

The remaining work to do on this:

- [ ] Send notifications when an existing listing's status changes to "active" (I have #907 out to address this)
- [ ] For the notifications for newly-created listings, make sure the new listing has status "active" (if not, don't send notifications).
- [ ] In https://github.com/CityOfDetroit/bloom/blob/main/backend/core/src/sms/services/sms.service.ts, update the SMS notification body (e.g. to include a link to the new listing, and possibly translate the message text).
- [ ] The current implementation retrieves a list of all users from the DB, and filters them by "should we send them a notification?" in https://github.com/CityOfDetroit/bloom/blob/main/backend/core/src/sms/services/sms.service.ts. A better-performance approach would be to do the filtering in the SQL query to the DB; this will require changes to `UserService` too.

**Comment by YazeedLoonat** [comment]
closing!
