### ISSUE TITLE
Add favorite listings capability

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#78]
- [x] sync with Exygy on plans - [discussion here](https://github.com/bloom-housing/bloom/discussions/1719)
- [x] [Design doc](https://detroitmigov.box.com/s/m5df2tn1xgnf5x2gf3e0waz4tyizhplt)
- [ ] Associate a list of favorites with the user account
- [ ] Add affordance in the UI
- [ ] Only display the favorite button when the user is logged in? Or require login if clicked.
- [ ] Connect the affordance clicked with editing the database to add a listing.

**QA NOTES**
go to https://detroit-public-dev.netlify.app/ 
without logging in go to the listing list and verify you do not have a favorite button
now log in
go back to the listing list
verify there are favorite buttons
favorite 1(or more) listings

navigate to the new favorite dashboard
verify the listings you favorited are listed on that dashboard

**Comment by tomgebauer** [comment]
Desktop list page:
![image](https://user-images.githubusercontent.com/3886741/133271558-9b22d18b-f58b-4a86-acca-a8f5bfcc06b5.png)

Desktop detail page:
![image](https://user-images.githubusercontent.com/3886741/133271794-f9fbcb52-f0e8-400f-9a3d-59f2ba84a7af.png)

**Comment by seanmalbert** [comment]
https://www.figma.com/file/ymKHAWFxakuVvc1vNDAmnm/bloom-public-browse?node-id=801%3A7385

**Comment by kathyccheng** [comment]
this is good
