### ISSUE TITLE
Add recent updates / freshness info in the UI

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#80]
- [ ] Check if it's available in Bloom already or we need to port it over from Dahlia
- [ ] Add the feature

**Comment by willrlin** [comment]
The field looks like it may already exist in bloom, so we can try to surface this in the UI somehow.

**Comment by pfeeny5** [comment]
Found in San Jose site:
![image](https://user-images.githubusercontent.com/82653098/127522764-1b3f279e-fbcf-4947-a288-5b953057848a.png)

Able to get similar listing details via:
```
<p className="text-xl">
   {t("listings.listingUpdated")}
   {": "}
   {moment(listing.updatedAt).format("MMM DD, YYYY")}
</p>
```

Need to decide where we would like this. Options are:

- [ ] Sidebar section like San Jose 
- [ ] Sidebar section replacing "Application Due" bar
- [ ] Overlay button - similar to below
![image](https://user-images.githubusercontent.com/82653098/127523354-c2bea513-2dc1-4a43-bb2c-735a9a999964.png)

**Comment by willrlin** [comment]
You can prototype something if there's nothing in the mocks about it yet and maybe when @tomgebauer gets back he can weigh in.
