### ISSUE TITLE
Add Detroit Resource center section

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#81]
Blocked by HRD collecting resources

- [ ] Work with Tom to determine if it should look like the Bloom resource section
- [ ] Work with HRD to determine what links and resources we need
- [ ] Link to HRC intake form
- [ ] Get Help section on homepage AND listing detail page

**Comment by willrlin** [comment]
Hi @ChelseaRucker, Milestone 10 is approaching in a few weeks, do you think we'll be on track to getting the content for these pages by end of August? Thanks!

**Comment by jnowell** [comment]
Safiya gave me the following rough draft of what she wants this page to look like: https://docs.google.com/document/d/16XULtYdy1XJ9aBBty-BlQe8nYbQlJ-s1w20-t8CrcJU/edit

She says to just add what's there for now and then she's going to ask some experts in their fields about what other resources we should list there.
